#Copyright (c) 2010 AFP Authors
#This source code is released under the terms of the
#MIT license. Please see the file LICENSE for license details.

include $(GOROOT)/src/Make.inc

TARG=afp/filters/echo
GOFILES=\
	echo.go

include $(GOROOT)/src/Make.pkg
