.ll 60n
.TH AFP-FMT 5 "DECEMBER 2010" PSU "User Manuals"
.SH NAME 
afp-fmt \- audio format used by afp internally
.SH OERVIEW

bytes             Meaning
  _____________
1|_____________| Header Version Number
1|_____________| Audio Channels
1|_____________| Sample Size
4|             | Sample Rate
 |             |
 |             |
 |_____________|
8|             | Content Length
 |             |
 |             |
 |             |
 |             |
 |             |
 |             |
 |_____________|
?|      .      | Content - Interleaved Linear PCM
        .       
 |      .      |
 |_____________|

.SH AUTHORS
Aaron Devore <adevore at cs.pdx.edu>
.br
K. Jon Harker <kjharke at cs.pdx.edu>
.br
Cory Kolbeck <ckolbeck at cs.pdx.edu>
.br
Eric Oconnel <eoc at cs.pdx.edu>
.SH "SEE ALSO"
.BR afp-dev (3),
.BR afp-fmt (5)
