.TH AFP 1 "DECEMBER 2010" Linux "User Manuals"
.SH NAME
afp \- audio filter pipeline
.SH SYNOPSIS
.B afp [-v] ([-f 
.I spec-file
.B ] | [
.I pipeline
.B ])
.SH DESCRIPTION
.B afp
constructs and runs an audio processing pipeline composed 
of a series of filters.  The pipeline is specified using a 
bang ('!') separated list of filters. The behavior of a 
given filter may be modified by passing it  

.SH OPTIONS
.IP -v
Verbose output
.IP "-f spec-file"
Read the pipeline spec from 
.I spec-file
instead of command line
.SH FILES
	None.
.SH BUGS
	Plenty.
.SH AUTHOR
Cory Kolbeck <ckolbeck at cs.pdx.edu>
.SH "SEE ALSO"
.BR afp-dev
