# Copyright (c) 2010 Go Fightclub Authors
# This source code is released under the terms of the
# MIT license. Please see the file LICENSE for license details.

include $(GOROOT)/src/Make.inc

TARG=afp/flags
GOFILES=flags.go


include $(GOROOT)/src/Make.pkg
